// Regenerates the per-domain barrel files (src/<domain>/index.ts) and the
// aggregate src/index.ts.
//
// The list of domains is derived from package.json "exports": every subpath
// entry (other than "." and "./package.json") whose import target looks like
// "./build/<folder>/index.js" contributes one barrel. package.json is the
// single authored source of truth for the public surface — add a subpath
// there, then run:
//
//   node scripts/generateDomainBarrels.mjs
//
// src/packageExports.test.ts guards the other direction: every src/<domain>
// folder that holds a shippable module must have a subpath here.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { join, relative, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const sourceDirectory = join(repositoryRoot, "src")

const domainFoldersFromPackageExports = () => {
    const { exports } = JSON.parse(
        readFileSync(join(repositoryRoot, "package.json"), "utf-8")
    )
    return Object.entries(exports)
        .filter(
            ([subpath]) =>
                subpath.startsWith("./") && subpath !== "./package.json"
        )
        .map(([subpath, exportEntry]) => {
            const importTarget =
                typeof exportEntry === "string"
                    ? exportEntry
                    : exportEntry.import
            const folderMatch = /^\.\/build\/(.+)\/index\.js$/.exec(
                importTarget ?? ""
            )
            if (folderMatch === null) {
                throw new Error(
                    `domainFoldersFromPackageExports: exports "${subpath}" does not point at a "./build/<folder>/index.js" barrel`
                )
            }
            return folderMatch[1]
        })
}

const findModuleFiles = (directory) => {
    let moduleFiles = []
    for (const entry of readdirSync(directory)) {
        const entryPath = join(directory, entry)
        if (statSync(entryPath).isDirectory()) {
            moduleFiles = moduleFiles.concat(findModuleFiles(entryPath))
        } else if (
            entry.endsWith(".ts") &&
            !entry.endsWith(".test.ts") &&
            entry !== "index.ts"
        ) {
            moduleFiles.push(entryPath)
        }
    }
    return moduleFiles
}

const relativeImportSpecifier = (fromDirectory, moduleFile) => {
    const specifier = relative(fromDirectory, moduleFile)
        .replace(/\\/g, "/")
        .replace(/\.ts$/, ".js")
    return specifier.startsWith(".") ? specifier : `./${specifier}`
}

const writeDomainBarrel = (domainFolder) => {
    const domainDirectory = join(sourceDirectory, domainFolder)
    const exportLines = findModuleFiles(domainDirectory)
        .sort()
        .map(
            (moduleFile) =>
                `export * from "${relativeImportSpecifier(domainDirectory, moduleFile)}"`
        )
    writeFileSync(
        join(domainDirectory, "index.ts"),
        exportLines.join("\n") + "\n"
    )
    console.log(`src/${domainFolder}/index.ts (${exportLines.length} modules)`)
}

const writeAggregateBarrel = (domainFolders) => {
    const header = [
        "// Aggregate public surface: re-exports every domain barrel.",
        '// Generated by scripts/generateDomainBarrels.mjs from package.json "exports".',
        "// Each domain is also individually importable via its package subpath",
        '// (e.g. "2025-11-battle-of-fell-desert-logic/mission").',
    ]
    const exportLines = domainFolders.map(
        (domainFolder) => `export * from "./${domainFolder}/index.js"`
    )
    writeFileSync(
        join(sourceDirectory, "index.ts"),
        [...header, ...exportLines].join("\n") + "\n"
    )
    console.log(`src/index.ts (${exportLines.length} domains)`)
}

const domainFolders = domainFoldersFromPackageExports()
domainFolders.forEach(writeDomainBarrel)
writeAggregateBarrel(domainFolders)
