// Aggregate public surface: re-exports every domain barrel.
// Generated by scripts/generateDomainBarrels.mjs from package.json "exports".
// Each domain is also individually importable via its package subpath
// (e.g. "2025-11-battle-of-fell-desert-logic/mission").
export * from "./aStarSearch/index.js"
export * from "./affiliation/index.js"
export * from "./campaign/index.js"
export * from "./coordinateMap/index.js"
export * from "./degreesOfSuccess/index.js"
export * from "./localization/index.js"
export * from "./mission/index.js"
export * from "./movie/index.js"
export * from "./priorityQueue/index.js"
export * from "./proficiency/index.js"
export * from "./resource/index.js"
export * from "./squad/index.js"
export * from "./squaddie/index.js"
export * from "./squaddieAction/index.js"
export * from "./squaddieItem/index.js"
